import {
  StartingSoonPage,
  MainCodingPage,
  BrbPage,
  BreakPage,
  WhiteboardPage,
  ProblemAnalysisPage,
  EndScreenPage,
} from '@/routes/codes/pages'
import { CodesChatPage } from '@/routes/codes/chat'
import { CalisthenicsChatPage } from '@/routes/calisthenics/chat'
import {
  CodesCameraFramePage,
  CodesChatFramePage,
  CalisthenicsCameraFramePage,
  CalisthenicsChatFramePage,
} from '@/routes/shared/frame-pages'
import {
  CalisthenicsMainPage,
  CalisthenicsBrbPage,
  CalisthenicsBreakPage,
  CalisthenicsReactPage,
  CalisthenicsEndScreenPage,
} from '@/routes/calisthenics/pages'
import type { SceneCatalogEntry } from '@/components/control/ScenePreviewCatalog'
import type { Scene } from '@/stores/types'

export const SCENE_CATALOG: SceneCatalogEntry[] = [
  {
    id: 'codes-starting-soon',
    label: 'Starting Soon',
    path: '/codes/starting-soon',
    scene: 'starting-soon',
    group: 'codes',
    Page: StartingSoonPage,
  },
  {
    id: 'codes-main',
    label: 'Main',
    path: '/codes/main',
    scene: 'live',
    group: 'codes',
    Page: MainCodingPage,
  },
  {
    id: 'codes-break',
    label: 'Break',
    path: '/codes/break',
    scene: 'break',
    group: 'codes',
    Page: BreakPage,
  },
  {
    id: 'codes-brb',
    label: 'BRB',
    path: '/codes/brb',
    scene: 'brb',
    group: 'codes',
    Page: BrbPage,
  },
  {
    id: 'codes-whiteboard',
    label: 'Whiteboard',
    path: '/codes/whiteboard',
    scene: 'whiteboard',
    group: 'codes',
    Page: WhiteboardPage,
  },
  {
    id: 'codes-problem-analysis',
    label: 'Problem Analysis',
    path: '/codes/problem-analysis',
    scene: 'problem-analysis',
    group: 'codes',
    Page: ProblemAnalysisPage,
  },
  {
    id: 'codes-end-screen',
    label: 'End Screen',
    path: '/codes/end-screen',
    scene: 'end-screen',
    group: 'codes',
    Page: EndScreenPage,
  },
  {
    id: 'codes-chat',
    label: 'Live Chat',
    path: '/codes/chat',
    scene: 'live',
    group: 'codes',
    Page: CodesChatPage,
  },
  {
    id: 'codes-camera-frame',
    label: 'Camera Frame',
    path: '/codes/camera-frame',
    scene: 'live',
    group: 'codes',
    Page: CodesCameraFramePage,
  },
  {
    id: 'codes-chat-frame',
    label: 'Chat Frame',
    path: '/codes/chat-frame',
    scene: 'live',
    group: 'codes',
    Page: CodesChatFramePage,
  },
  {
    id: 'cal-main',
    label: 'Main Workout',
    path: '/calisthenics/main',
    scene: 'workout',
    group: 'calisthenics',
    Page: CalisthenicsMainPage,
  },
  {
    id: 'cal-break',
    label: 'Break',
    path: '/calisthenics/break',
    scene: 'break',
    group: 'calisthenics',
    Page: CalisthenicsBreakPage,
  },
  {
    id: 'cal-brb',
    label: 'BRB',
    path: '/calisthenics/brb',
    scene: 'brb',
    group: 'calisthenics',
    Page: CalisthenicsBrbPage,
  },
  {
    id: 'cal-react',
    label: 'React Alert',
    path: '/calisthenics/react',
    scene: 'react',
    group: 'calisthenics',
    Page: CalisthenicsReactPage,
  },
  {
    id: 'cal-end-screen',
    label: 'End Screen',
    path: '/calisthenics/end-screen',
    scene: 'end-screen',
    group: 'calisthenics',
    Page: CalisthenicsEndScreenPage,
  },
  {
    id: 'cal-chat',
    label: 'Live Chat',
    path: '/calisthenics/chat',
    scene: 'workout',
    group: 'calisthenics',
    Page: CalisthenicsChatPage,
  },
  {
    id: 'cal-camera-frame',
    label: 'Camera Frame',
    path: '/calisthenics/camera-frame',
    scene: 'workout',
    group: 'calisthenics',
    Page: CalisthenicsCameraFramePage,
  },
  {
    id: 'cal-chat-frame',
    label: 'Chat Frame',
    path: '/calisthenics/chat-frame',
    scene: 'workout',
    group: 'calisthenics',
    Page: CalisthenicsChatFramePage,
  },
]

export const CONTROL_SCENES: { id: Scene; label: string }[] = [
  { id: 'offline', label: 'Offline' },
  { id: 'starting-soon', label: 'Starting Soon' },
  { id: 'live', label: 'Main' },
  { id: 'break', label: 'Break' },
  { id: 'brb', label: 'BRB' },
  { id: 'whiteboard', label: 'Whiteboard' },
  { id: 'problem-analysis', label: 'Problem Analysis' },
  { id: 'end-screen', label: 'End Screen' },
  { id: 'workout', label: 'Workout' },
  { id: 'react', label: 'React' },
]
